// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.imag.professionalinfo.domain;

import fr.imag.professionalinfo.domain.Inventeur;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Inventeur_Roo_Configurable {
    
    declare @type: Inventeur: @Configurable;
    
}
