// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.imag.professionalinfo.domain;

import fr.imag.professionalinfo.domain.Langage;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Langage_Roo_Configurable {
    
    declare @type: Langage: @Configurable;
    
}
