//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inscription.WebUI.InscriptionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuitMatiere", Namespace="http://schemas.datacontract.org/2004/07/Inscription.WebServices.DataModel")]
    [System.SerializableAttribute()]
    public partial class SuitMatiere : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnneeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEtudiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMatiereField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Annee {
            get {
                return this.AnneeField;
            }
            set {
                if ((object.ReferenceEquals(this.AnneeField, value) != true)) {
                    this.AnneeField = value;
                    this.RaisePropertyChanged("Annee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEtudiant {
            get {
                return this.IdEtudiantField;
            }
            set {
                if ((this.IdEtudiantField.Equals(value) != true)) {
                    this.IdEtudiantField = value;
                    this.RaisePropertyChanged("IdEtudiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMatiere {
            get {
                return this.IdMatiereField;
            }
            set {
                if ((this.IdMatiereField.Equals(value) != true)) {
                    this.IdMatiereField = value;
                    this.RaisePropertyChanged("IdMatiere");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InscriptionService.IInscriptionService")]
    public interface IInscriptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/addMS", ReplyAction="http://tempuri.org/IInscriptionService/addMSResponse")]
        void addMS(Inscription.WebUI.InscriptionService.SuitMatiere MS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/getMS", ReplyAction="http://tempuri.org/IInscriptionService/getMSResponse")]
        System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/getMSByEtudiant", ReplyAction="http://tempuri.org/IInscriptionService/getMSByEtudiantResponse")]
        System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMSByEtudiant(int idEtudiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/getMSByMatiere", ReplyAction="http://tempuri.org/IInscriptionService/getMSByMatiereResponse")]
        System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMSByMatiere(int idMatiere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/deleteMS", ReplyAction="http://tempuri.org/IInscriptionService/deleteMSResponse")]
        void deleteMS(int idEtudiant, int idMatiere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/deleteMSByEtudiant", ReplyAction="http://tempuri.org/IInscriptionService/deleteMSByEtudiantResponse")]
        void deleteMSByEtudiant(int idEtudiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInscriptionService/deleteMSByMatiere", ReplyAction="http://tempuri.org/IInscriptionService/deleteMSByMatiereResponse")]
        void deleteMSByMatiere(int idMatiere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInscriptionServiceChannel : Inscription.WebUI.InscriptionService.IInscriptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscriptionServiceClient : System.ServiceModel.ClientBase<Inscription.WebUI.InscriptionService.IInscriptionService>, Inscription.WebUI.InscriptionService.IInscriptionService {
        
        public InscriptionServiceClient() {
        }
        
        public InscriptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InscriptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscriptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InscriptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addMS(Inscription.WebUI.InscriptionService.SuitMatiere MS) {
            base.Channel.addMS(MS);
        }
        
        public System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMS() {
            return base.Channel.getMS();
        }
        
        public System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMSByEtudiant(int idEtudiant) {
            return base.Channel.getMSByEtudiant(idEtudiant);
        }
        
        public System.Collections.Generic.List<Inscription.WebUI.InscriptionService.SuitMatiere> getMSByMatiere(int idMatiere) {
            return base.Channel.getMSByMatiere(idMatiere);
        }
        
        public void deleteMS(int idEtudiant, int idMatiere) {
            base.Channel.deleteMS(idEtudiant, idMatiere);
        }
        
        public void deleteMSByEtudiant(int idEtudiant) {
            base.Channel.deleteMSByEtudiant(idEtudiant);
        }
        
        public void deleteMSByMatiere(int idMatiere) {
            base.Channel.deleteMSByMatiere(idMatiere);
        }
    }
}
